### ISSUE TITLE
Make vpm.json visible like package.json

### ISSUE THREAD

**Issue by AtjonTV** [yue-best-practices/vpm#2]
For me it makes more sense to be able to see the vpm.json file (like the package.json of NPM).

The current name is `.vpm.json` which makes it invisiable when using default settings on most file managers.

It makes no sense to not be able to see your package list/project file, does it?

**Comment by nedpals** [comment]
Hi! Apologies if this is the wrong place to discuss about this one. I'm building a similar thing called [vpkg](https://github.com/nedpals/vpkg) and I kinda think we should have a single, unified, standardized/spec'd package information file and lockfile (`vpm.json` or [`.vpkg.json`](https://github.com/nedpals/vpkg/blob/master/.vpkg.json) in this case) so users can use it without any problems at all (much like Yarn is fully compatible with NPM except the lockfile).

**Comment by Smartyue** [comment]
Yeah it’s a good idea!


发自我的iPhone

------------------ Original ------------------
