### ISSUE TITLE
网站上没法提交 module

### ISSUE THREAD

**Issue by taojy123** [yue-best-practices/vpm#8]
你好，
我开发了一个 web 框架，想发布到 vpm 上。
我在 https://vpm.best 上先点 Submit a module。
然后点 Log in via GitHub。
跳转授权都正常的，但是最后 redirect 回 https://vpm.best/new 并没有登录上，页面依旧是没登陆的样子。

我要提交的 module 叫 valval，是一个 web 开发框架。
官网地址是 https://valval.cool/
github 地址是 https://github.com/taojy123/valval

希望能吸纳我这项目进 vpm
谢谢！

**Comment by Smartyue** [comment]
你好。
vpm.best域名不是我在维护，而是v语言作者，建议你在v语言github上提issues。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: taojy123 <notifications@github.com&gt;
发送时间: 2019年12月17日 14:14
收件人: yue-best-practices/vpm <vpm@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[yue-best-practices/vpm] 网站上没法提交 module (#8)




你好，
 我开发了一个 web 框架，想发布到 vpm 上。
 我在 https://vpm.best 上先点 Submit a module。
 然后点 Log in via GitHub。
 跳转授权都正常的，但是最后 redirect 回 https://vpm.best/new 并没有登录上，页面依旧是没登陆的样子。
 
我要提交的 module 叫 valval，是一个 web 开发框架。
 官网地址是 https://valval.cool/
 github 地址是 https://github.com/taojy123/valval
 
希望能吸纳我这项目进 vpm
 谢谢！

**Comment by taojy123** [comment]
哦哦，原来是这样，我已经在 v 项目是提了 issue 了，可好像其他都都无法重现这个问题。难道是天朝的网络问题，我也试过用 vpn 一样不行。 你方便试下现在你的账号能否正常登陆 vpm 吗？




| |
陶佳元
邮箱：taojy123@163.com
|

签名由 网易邮箱大师 定制

在2019年12月17日 16:12，Smartyue 写道：
你好。
vpm.best域名不是我在维护，而是v语言作者，建议你在v语言github上提issues。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: taojy123 <notifications@github.com&gt;
发送时间: 2019年12月17日 14:14
收件人: yue-best-practices/vpm <vpm@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[yue-best-practices/vpm] 网站上没法提交 module (#8)




你好，
我开发了一个 web 框架，想发布到 vpm 上。
我在 https://vpm.best 上先点 Submit a module。
然后点 Log in via GitHub。
跳转授权都正常的，但是最后 redirect 回 https://vpm.best/new 并没有登录上，页面依旧是没登陆的样子。

我要提交的 module 叫 valval，是一个 web 开发框架。
官网地址是 https://valval.cool/
github 地址是 https://github.com/taojy123/valval

希望能吸纳我这项目进 vpm
谢谢！

**Comment by Smartyue** [comment]
我刚试了下，没用vpn也是可以登录成功的。

我这里是用的电信宽带。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: taojy123 <notifications@github.com&gt;
发送时间: 2019年12月17日 18:52
收件人: yue-best-practices/vpm <vpm@noreply.github.com&gt;
抄送: Smartyue <1814888800@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[yue-best-practices/vpm] 网站上没法提交 module (#8)



哦哦，原来是这样，我已经在 v 项目是提了 issue 了，可好像其他都都无法重现这个问题。难道是天朝的网络问题，我也试过用 vpn 一样不行。 你方便试下现在你的账号能否正常登陆 vpm 吗？
 
 
 
 
 | |
 陶佳元
 邮箱：taojy123@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2019年12月17日 16:12，Smartyue 写道：
 你好。
 vpm.best域名不是我在维护，而是v语言作者，建议你在v语言github上提issues。
 
 
 
 发自我的iPhone
 
 
 ------------------ 原始邮件 ------------------
 发件人: taojy123 <notifications@github.com&amp;gt;
 发送时间: 2019年12月17日 14:14
 收件人: yue-best-practices/vpm <vpm@noreply.github.com&amp;gt;
 抄送: Subscribed <subscribed@noreply.github.com&amp;gt;
 主题: 回复：[yue-best-practices/vpm] 网站上没法提交 module (#8)
 
 
 
 
 你好，
 我开发了一个 web 框架，想发布到 vpm 上。
 我在 https://vpm.best 上先点 Submit a module。
 然后点 Log in via GitHub。
 跳转授权都正常的，但是最后 redirect 回 https://vpm.best/new 并没有登录上，页面依旧是没登陆的样子。
 
 我要提交的 module 叫 valval，是一个 web 开发框架。
 官网地址是 https://valval.cool/
 github 地址是 https://github.com/taojy123/valval
 
 希望能吸纳我这项目进 vpm
 谢谢！

**Comment by taojy123** [comment]
好的 谢谢，要么是我的账号有问题，我试试用其他账号能否正常登陆
